#cloud-config
hostname: ${host_name}
#packages:
#  - vim
#  - git
ssh_pwauth: true
disable_root: false
chpasswd:
  list: |
     root:password
  expire: false
users:
  - name: k8s
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    lock_passwd: false
    ssh-authorized-keys:
      - ${pub_key}

runcmd:
  - netplan apply
  - sudo apt update -y
  - sudo apt upgrade -y
  - sudo apt install -y qemu-guest-agent
  - sudo systemctl enable qemu-guest-agent
  - sudo systemctl start qemu-guest-agent
  #- sudo apt install -y apt-transport-https ca-certificates curl
  #- sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
  #- echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  #- sudo apt update
  #- sudo apt install -y kubelet=1.26.3-00 kubeadm=1.26.3-00 kubectl=1.26.3-00
  #- sudo apt hold kubelet kubeadm kubectl

  #- [ sed, -i, 's/PasswordAuthentication no/PasswordAuthentication yes/g', /etc/ssh/sshd_config ]
  #- systemctl restart sshd
  #- [ apt, update ]
  #- [ apt, install, -y, cloud-init ]
  #- [ cloud-init, init ]
  #- [ cloud-init, modules, --mode, config ]
  #- [ cloud-init, modules, --mode, final ]
# tbd enable qemu guest agent
 # package_update: true
 #           
 #           
 #           packages:
 #             - qemu-guest-agent
 #           
 #           runcmd:
 #             - [ systemctl, enable, qemu-guest-agent.service ]
 #             - [ systemctl, start, qemu-guest-agent.service ]

final_message: "The system is finally up, after $UPTIME seconds"
