ethernets:
    ${interface_name}:
        addresses: 
        - ${ip_addr}/24
        dhcp4: false
        dhcp6: false
        nameservers:
            addresses: 
            - 1.1.1.1
            - 8.8.8.8
        routes: 
          - to: default
            via: 192.168.40.1
        match:
          name: en*
        set-name: ${interface_name}
version: 2